site_name: Fiori Tracker
site_url: https://fioritracker.org
nav:
    - User manual: user-manual.md
    - Learn more: learn-more.md
    - Installation: inst.md
    - Support: support.md  
    - Philosophy: philosophy.md   
    - Impressum: impressum.md
theme: 
  name: 'material'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.png'
  custom_dir: overrides
extra_css:
  - stylesheets/extra.css  
markdown_extensions:
  - markdown_include.include:
        base_path: docs
  - admonition  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - macros
  - search
copyright: Copyright &copy; 2016 - 2024 Nype
extra:
  analytics:
    provider: google
    property: G-3SXC9PW73K 
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/fiori-tracker/
    - icon: fontawesome/brands/twitter
      link: http://twitter.com/fioritracker
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC6bx5QiaM3KRE8qgshBrurg
  prod:  
    core:
      name: 'Fiori Tracker Core'
      desc: 'Applications and Catalogs "To-be" records and their association'
      nameshort: 'Core'
      main: '2020'
      latestrel: 'SPS03'
      cen: 'X'
      man: ' '
      rep: 'installation'
      pay: 'free'
    asisCen:
      name: 'As-is main: API'
      desc: 'Enables Managed systems data synchronization'
      nameshort: 'As-is API'
      main: '2020'
      latestrel: 'SPS02'
      cen: 'X'
      man: ' '
      rep: 'asis-cen'
      pay: 'free'
    asisMan:
      name: 'As-is Connector'
      main: '2020'
      latestrel: 'SPS02'
      cen: 'X'
      man: 'X'
      rep: 'asis-man'
      pay: 'free'
    catAppRep:
      name: 'Catalog and App reports'
      desc: 'Catalog and Apps "As-is" records and their association'
      main: '2020'
      latestrel: 'SPS02'
      cen: 'X'
      man: ' '
      rep: 'catapprep'
      pay: 'free'  
    cr:
      name: 'Catalog Report'
      main: '2020'
      latestrel: 'SPS02'
      cen: 'X'
      man: ' '
      rep: 'cat-rep'
      pay: 'free'
    ac:
      name: 'App Catalogs Report'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'ac'
      pay: 'free'
    ca:
      name: 'Catalog Apps Report'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'ca'
      pay: 'free'
    fa:
      name: 'Fiori Apps Usage Report'
      desc: 'Fiori Apps Usage Report is a component that enables collecting usage records.'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'fa'
      pay: 'paid'
    fap:
      name: 'Fiori Apps Usage Plugin'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: 'X'
      rep: 'fap'
      pay: 'paid'
    ftCatsRelAppsAsis:
      name: 'FT Catalogs Relation: Apps As-is'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'asis-cen'
      pay: 'free'
    ftAppsRelCatsAsis:
      name: 'FT Apps Relation: Catalogs, As-is'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'asis-cen'
      pay: 'free'
    ftAppsRelAppsUsage:
      name: 'FT Apps Relation: Apps` Usage'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'fa'
      pay: 'paid'
    ch:
      name: 'Change Requests'
      desc: 'Change request records linked to catalogs and apps'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'ch'
      pay: 'free'
    RelCh:
      name: 'FT Apps and Catalogs Relation: Change Requests'
      desc: 'The Change Request relation shows a list of change requests linked to an application or catalog.'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'ch'
      pay: 'free'  
    so:
      name: 'Sign-offs'
      desc: 'The Sign-offs app lets you create, change and list sign-offs records linked to all content types (apps, catalogs and roles)'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'so'
      pay: 'free'
    tu:
      name: 'Test users'
      nameshort: 'Test users'
      desc: 'The Test users app lets you create, change, and list test user records.'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'tu'
      pay: 'free'
    RelTu:
      name: 'FT Apps Relation: Test users'
      desc: 'The Test users relation shows a list of test users linked to all apps'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'tu'
      pay: 'free'      
    hi:
      name: 'History'
      nameshort: 'History'
      desc: 'The History component keeps the history records for SAP Fiori launchpad key deliverables: apps, catalogs, and roles.'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'hi'
      pay: 'free'
    co:
      name: 'Comments'
      nameshort: 'Comments'
      desc: 'The Comments component keeps the free text notes records for SAP Fiori launchpad key deliverables: apps, catalogs, and roles.'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'co'
      pay: 'free'
    RelSo:
      name: 'FT Apps and Catalogs Relation: Sign-offs'
      desc: 'The Sign-offs relation shows a list of sign-offs linked to all content types (apps, catalogs and roles)'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'so'
      pay: 'free'
    ro:
      name: 'Fiori Tracker Roles'
      nameshort: 'Roles'
      desc: 'Roles "To-be" records and their association to apps through catalogs'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'ro'
      pay: 'free'
    ci:
      name: 'Catalog Import'
      nameshort: 'Catalog Import'
      desc: 'Lets you import catalogs from your system into the "To-be" catalogs list'
      main: '2020'
      latestrel: 'SPS02'
      cen: 'X'
      man: ' '
      rep: 'ci'
      pay: 'paid'
    ai:
      name: 'Application Import'
      nameshort: 'Apps Import'
      desc: 'Lets you import applications from your system into the "To-be" application list'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'ai'
      pay: 'paid'
    mi:
      name: 'Mapping Import'
      nameshort: 'Mapping Import'
      desc: 'Lets you import mappings of the applications to catalogs'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'mi'
      pay: 'paid'
    RelRo:
      name: 'FT Apps and Catalogs Relation: Roles'
      desc: 'The Roles relation shows a list of sign-offs linked to all content types (apps, catalogs and roles)'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'ro'
      pay: 'free'
    gv:
      name: 'Gover'
      nameshort: 'Gover'
      desc: 'Gover is a solution that enables security checks for your SAP system landscape.'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'gv'
      pay: 'paid'
